name: DecaliumCustomItems
version: ${project.version}
main: me.gepronix.decaliumcustomitems.DecaliumCustomItems
api-version: 1.16
authors: [ gepronix ]
depend:
  - ProtocolLib
description: super cool
commands:
  customitem:

