name: DecaliumCustomItems
version: 1.1.1
main: com.manya.decaliumcustomitems.DecaliumCustomItems
api-version: 1.16
authors: [ manya ]
depend:
  - ProtocolLib
description: super cool
commands:
  customitem:

