name: DecaliumCustomItems
version: 1.1.1
main: me.gepron1x.decaliumcustomitems.DecaliumCustomItems
api-version: 1.16
authors: [ gepron1x ]
depend:
  - ProtocolLib
description: super cool
commands:
  customitem:

